<?php
/** @var \App\Models\Project[] $projects */
?>

<?php if (is_array($projects) && count($projects) > 0): ?>
    <table class="table table-bordered table-striped table-hover">
        <thead>
        <tr>
            <th>Domain</th>
            <th>Name</th>
            <th width="100">Type</th>
            <th width="150">Erstellt am</th>
            <th width="125">Optionen</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($projects as $p): ?>
            <?php $label = ($p->getType() === 'shop') ? 'info' : 'default' ?>
            <tr>
                <th>
                    <a href="<?php echo $p->getExternalUrl() ?>" target="_blank"><?php echo $p->getUrl() ?></a>
                    <?php if (false !== $dbUrl && false !== ($dbAdmin = $p->getDbUrl())): ?>
                        <a href="<?php echo $dbAdmin ?>" target="_blank"  title="Datenbank Admin" class="pull-right btn btn-default btn-xs">
                            <span class="fa fa-database"></span>
                        </a>
                    <?php endif; ?>
                </th>
                <td><?php echo $p->getName() ?></td>
                <td><span class="label label-<?php echo $label ?>"><?php echo $p->getType() ?></span></td>
                <td><?php echo $p->getCreatedDate() ?></td>
                <td>
                    <a href="#" title="Projekt hochladen" class="pull-right btn btn-default btn-sm"><span class="fa fa-cloud-upload"></span></a>
                    <a href="#" style="background-color: red" title="Projekt löschen" class="pull-right btn btn-default btn-sm"><span class="fa fa-times"></span></a>
                    <a href="#" title="Projekt Einstellungen" class="pull-right btn btn-default btn-sm"><span class="fa fa-cogs"></span></a>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php else: ?>
    <p class="lead text-center">Keine Projekte vorhanden</p>
<?php endif; ?>