

<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <div class="page-header">
            <h1>Project<small> manager</small></h1>
        </div>
        <form method="POST" action="">
            <div class="form-group form-group-lg">
                <input type="text" class="form-control" name="user" placeholder="User">
            </div>
            <div class="row">
                <div class="col-md-8">
                    <div class="form-group form-group-lg">
                        <input type="password" class="form-control" name="pass" placeholder="Passwort">
                    </div>
                </div>
                <div class="col-md-4">
                    <button class="btn btn-block btn-lg btn-primary" type="submit">
                        Login
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>