<?php
/**
 * Copyright (c) 2018.  MyArtSide
 */

/**
	 * Created by PhpStorm.
	 * User: user3
	 * Date: 04.04.2018
	 * Time: 11:56
	 */
?>
<!--
<div class="iframe-container">
	<iframe name="iframe-page-container" src="sysinfo.cgi"></iframe>
</div>
-->
<div class="container page-container">
        <?php if (isset($user)): ?>
	        <div class="page-header">
                <h1><a href="/"><?php echo $user->name ?></a>
                    <small><?php echo 'udev ' ?></small>
                    <div class="btn-toolbar pull-right">
                        <?php if ($user->isAdmin()): ?>

                        <?php else: ?>
	                        <a href="#" class="btn btn-lg btn-success" data-toggle="modal" data-target=".new-modal">
                                <span class="glyphicon glyphicon-plus"></span>
                            </a>

                        <?php endif; ?>
	
	                    <a href="?controller=project&action=stats" class="btn btn-lg btn-default">
                            <span class="glyphicon glyphicon-stats"></span>
                        </a>

                        <div class="btn-group">
                            <button class="btn btn-default btn-lg dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="glyphicon glyphicon-user"></span>
                            </button>
                            <ul class="dropdown-menu dropdown-menu-right">
                                <li class="dropdown-header">
                                    Angemeldet als <?php echo $user->fullname ?>
                                </li>
                                <li>
                                    <a href="#" data-toggle="modal" data-target=".logout-modal">ausloggen</a>
                                </li>
								<li class="dropdown-header">
									Einstellungen
								</li>
								<li>
                                    <a href="#" data-toggle="modal" data-target=".settings-modal">Benutzer Einstellungen</a>
                                </li>
                            </ul>
                        </div>

                    </div>
                </h1>
            </div>
        <?php endif; ?>
		<?php foreach (\Core\Di::getFlash()->getMessages() as $message): ?>
			<?php echo $message->render() ?>
		<?php endforeach; ?>
		<?php echo $this->getContent() ?>
    </div>

