<?php
/**
 * Copyright (c) 2018.  MyArtSide
 */

/**
	 * Created by PhpStorm.
	 * User: user3
	 * Date: 04.04.2018
	 * Time: 11:07
	 */
?>
<nav class="navbar navbar-default navbar-webmin navbar-fixed-top" role="navigation">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle navbar-toggle-webmin" data-toggle="collapse" data-target="#navbar-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="http://udev/"><i class="fa fa-cloud"></i><?php echo ' CMS Projektverwaltung' ?> <span></span></a>
		</div>
		<div class="collapse navbar-collapse" id="navbar-collapse">
			<ul class="nav navbar-nav">
				<li class="visible-xs"><a data-toggle="collapse" data-target="#navbar-collapse" target="container" href="/"><i class="fa fa-tags"></i> Main Menu</a></li>
				<li><a data-toggle="collapse" data-target="#navbar-collapse" target="container" href="?controller=project&action=stats"><i class="fa fa-file-text"></i> Stats</a></li>
				<!--<li><a data-toggle="collapse" data-target="#navbar-collapse" target="page-container" href="/webmin/refresh_modules.cgi"><i class="fa fa-refresh"></i> Refresh</a></li>-->
				<li><a href="#" class="btn btn-lg btn-success" data-toggle="modal" data-target=".new-modal" target="container"><i class="fa fa-plus"></i> Neu</a></li>
			</ul>
			<div class="navbar-right">
				<p class="navbar-text pull-left">Willkommen, <a href="#" data-toggle="modal" data-target=".settings-modal" target="container"><?php echo $user->fullname ?></a></p>
				<a href="#" data-toggle="modal" data-target=".logout-modal" target="container" class="btn btn-bwtheme btn-danger navbar-btn pull-right"><i class="fa fa-sign-out"></i> Logout</a>
			</div>
		</div>
	</div>
</nav>